"""change genres to json

Revision ID: 95462e8aa6ff
Revises: b38fdbbb705d
Create Date: 2026-03-26 14:41:07.061402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95462e8aa6ff'
down_revision: Union[str, Sequence[str], None] = 'b38fdbbb705d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='to_jsonb(genres)::json')
            
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'genres',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False,
               postgresql_using='genres::text[]')
    # ### end Alembic commands ###
